apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: ingress
  namespace: ingress-nginx
spec:
  egress:
  - hosts:
    # any service in the application-ns namespace (to communicate with the application)
    - "application-ns/*"
    # any service in the aks-istio-system namespace (to communicate with the istio control plane)
    - "aks-istio-system/*"
